#!/usr/bin/env python

import sys

if "systemd" in sys.argv:
    from systemd_service import Service

    daemon = Service("stream_eeg", "stream_eeg")
    daemon.create_timer(on_boot_sec=10, after='network.target kafka.service')

else:
    from openbci_stream.daemons.stream_eeg import EEG

    print("Run 'stream_eeg systemd' as superuser for create the daemon.")
    tranformer = EEG()
    tranformer.consume()


