#!/usr/bin/env python

import sys

if "systemd" in sys.argv:
    from systemd_service import Service

    daemon0 = Service("stream_bin2eeg0", "stream_bin2eeg 0")
    daemon0.create_timer(
        on_boot_sec=10, after='network.target kafka.service')

    daemon1 = Service("stream_bin2eeg1", "stream_bin2eeg 1")
    daemon1.create_timer(
        on_boot_sec=10, after='network.target kafka.service')

    daemon2 = Service("stream_bin2eeg2", "stream_bin2eeg 2")
    daemon2.create_timer(
        on_boot_sec=10, after='network.target kafka.service')

    daemon3 = Service("stream_bin2eeg3", "stream_bin2eeg 3")
    daemon3.create_timer(
        on_boot_sec=10, after='network.target kafka.service')
else:
    from openbci_stream.daemons.stream_bin2eeg import BinaryToEEG

    print("Run 'stream_bin2eeg systemd' as superuser for create the daemon.")
    print(f"Collecting from topic 'eeg{sys.argv[1]}'")
    tranformer = BinaryToEEG(sys.argv[1])
    tranformer.consume()


